spring:
  application:
    name: profitly
  datasource:
    url: jdbc:postgresql://localhost:5432/profitly_db?currentSchema=public&stringtype=unspecified&serverTimezone=Asia/Kolkata
    username: profitly_user
    password: profitly_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${PROFITLY_JWT_SECRET}
  expirationMs: 86400000
  tokenPrefix: Bearer
